--- #YAML:1.0
name:               Linux-Proc-Cpuinfo
version:            0.01
abstract:           XS wrapper for libproccpuinfo - a generic parser for /proc/cpuinfo
author:
    - Alan Haggai Alavi <alanhaggai@alanhaggai.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    repository:
        type:  git
        url:   git://github.com/alanhaggai/Linux-Proc-Cpuinfo.git
        web:   http://github.com/alanhaggai/Linux-Proc-Cpuinfo
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
